services:
  # ─── 1. DATABASE CONTAINER ───
  db:
    image: postgres:15-alpine
    container_name: mypostgresdb_run
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       DATABASE_URL: ${DATABASE_URL}
       
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ─── 2. BACKEND CONTAINER ───
  backend:
    image: swapnaraut28/mybackend:latest
    build: ./backend
    container_name: mybackend_run
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./backend/app:/app

  # ─── 3. FRONTEND CONTAINER ───
  frontend:
    image: swapnaraut28/myfrontend:latest
    build: ./frontend
    container_name: myfrontend_run
    ports:
      - "5173:5173"  # Maps port 5173 of the container to localhost:5173 on your machine
    volumes:
      - /node_modules   # Anonymous volume: Prevents host node_modules from overwriting container
      - /tmp/.vite_cache # Anonymous volume: Keeps the Vite cache isolated in container RAM
    environment:
      - REACT_APP_API_URL=http://localhost:8000  # Tells React where to find the FastAPI backend
    depends_on:
      - backend

volumes:
  postgres_data: